server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s
      routes:
        - id: ms-pagamentos
          uri: lb://MS-PAGAMENTOS
          predicates:
            - Path=/alurafood/pagamentos/**
          filters:
            - RewritePath=/alurafood/pagamentos(?<segment>/?.*), $\{segment}
