server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s
      routes:
        - id: ms-pagamentos
          uri: lb://MS-PAGAMENTOS
          predicates:
            - Path=/alurafood/**
          filters:
            - RewritePath=/alurafood(?<segment>/?.*), $\{segment}

logging:
  level:
    br.com.alurafood.gateway.*: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-}]"
