spring:
  application:
    name: ms-pagamentos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/alurafood-pagamento?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    password: root
    username: root
  jpa:
    show-sql: true

eureka:
  instance:
    instance-id:
      ${spring.application.name}:${random.int}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      atualizaPedido:
        slidingWindowSize: 3
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 50s

ms-pedidos-name: ms-pedidos
